GHDL=ghdl
FLAGS="--std=08"

all:
	#@$(GHDL) -a $(FLAGS) MovingLed.vhd MovingLedTB.vhd
	#@$(GHDL) -a $(FLAGS) BarLedDriver.vhd BarLedDriverTB.vhd
	@$(GHDL) -a $(FLAGS) MovingLed_Basys3.vhd

	#@$(GHDL) -e $(FLAGS) MovingLedTB
	#@$(GHDL) -e $(FLAGS) BarLedDriverTB

	#@$(GHDL) -r $(FLAGS) MovingLedTB --wave=MovingLedWave.ghw --stop-time=4us
	#@$(GHDL) -r $(FLAGS) BarLedDriverTB --wave=BarLedWave.ghw --stop-time=1us

